cvc5/ethos

proofs/examples/programs.smt2, proofs/examples/resolution.smt2, proofs/examples/simple_uf.smt2, proofs/rules/Booleans.smt2, proofs/rules/Uf.smt2, proofs/theories/BitVectors.smt2, proofs/theories/Ints.smt2, proofs/theories/Reals.smt2, src/cmd_parser.cpp, src/main.cpp, src/state.cpp, src/state.h, tests/simple-include.smt2
`include` is now relative to the current file.  I used the `filesystem` standard library to implement this.  Seems to be more reliable then ad-hoc solutions.
Furthermore, this makes `args` and `premises` optional in `step`, but fixes the order.
=> Change the behavior of `step` and `include`

proofs/examples/booleans.smt2, proofs/examples/nary.smt2, proofs/programs/Booleans.smt2, proofs/programs/Nary.smt2, proofs/programs/Utils.smt2, proofs/rules/Booleans.smt2, proofs/rules/Uf.smt2, src/state.cpp, tests/not_and.smt2
This adds the remaining boolean rules and splits the programs into programs just for lists, and programs for Boolean lists.
There is also one tiny bugfix to the `include` mechanism in `alfc`.  It did not correctly return to the base file after an include.  That is
```
(include "a/b.smt2")
(include "c/d.smt2")
```
would fail, because it `alftc` would attempt to include `a/c/d.smt2`.
=> Refactor and add Boolean Rules

src/integer.h
See: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
=> Include cstdint to fix compilation on gcc 13

src/type_checker.cpp
The check for the Quote downcast iterrats over the type using the number of actual arguments.  If the number of actual arguments greater than the arguments in the type this leads to a null pointer dereference.
The solution is to perform the check if the arity is correct earlier.
=> Fix crash when number of arguments does not correspond to type

proofs/examples/booleans.smt2, proofs/examples/nary.smt2, proofs/programs/Booleans.smt2, proofs/programs/Nary.smt2
This broke with the move towards abstract nil-values.  Before the nil in the case of `or` was the value `false`.  However, with the change resulution to the empty clause would return `alf.nil` instead of `false`.
=> Fix resolution to false.

src/compiler.cpp, src/compiler.h, src/main.cpp, src/state.cpp, src/state.h, src/util/filesystem.cpp, src/util/filesystem.h
This adds a naive filepath handler that doesn't rely on the C++ filepath API.
Should throw an error when run on Windows.  I think in the future we should detect if the filepath API is available (how?) and use that one in case it is.
=> Handle filepaths without C++ 17 filepath library

src/attr.cpp, src/attr.h, src/expr_parser.cpp, src/expr_parser.h, src/main.cpp, src/parser.cpp, src/state.cpp, src/state.h, tests/CMakeLists.txt, tests/binder-ex.smt3
This allows a more SMT-LIB compliant syntax for binders.
=> Implementation of :binder

src/base/run.cpp
This handles the return values of the system calls that setup the pipes and that writes into the pipe.  A non-zero return value indicates an error.
To keep things simple, an incomplete write to the pipe is also considered an error.
This should stop the warnings here.
=> Handle system call return values in oracle runner

src/cmd_parser.cpp, tests/CMakeLists.txt, tests/mutual-rec.smt3
Syntax is to omit the program body.
This allows us to define mutually recursive programs.  Adds a regression that is an example of this.
=> Allow forward declarations of programs

src/kind.cpp, src/kind.h, src/state.cpp, src/type_checker.cpp, tests/Booleans-rules.smt3, tests/Sets-theory.smt3, tests/Strings-programs.smt3, tests/examples-nary.smt3, tests/or-concat-false.smt3, tests/rare-example.smt3, user_manual.md
The motivation is to disambiguate different arities for the overloaded operators, which simplifies parsing and type checking.
=> Update syntax for list operators

src/cmd_parser.cpp, user_manual.md
This is required to support further syntax differences in a backwards compatible manner.
Currently `program` and `declare-rule` are the two commands which I consider whose syntax should not be considered authoritative in our input format, although perhaps more should be considered.
=> Make syntax for declare-rule and program extensible

src/cmd_parser.cpp, src/main.cpp, src/state.cpp, src/state.h, user_manual.md
We no longer seek to accept smt3 verbatim.
Also corrects some misclassified commands in the parser.
=> Remove strict parse option

src/state.cpp, src/state.h, tests/CMakeLists.txt, tests/disamb-arith.smt3, user_manual.md
The order of declarations from the user is now interpreted as the precedence order.
This means the user needs to declare e.g. unary `-` before binary `-` to achieve the expected result.
I open to making this policy e.g. configurable by an option later if needed.
=> Update policy for disambiguating overloads

src/state.cpp, tests/arity-overload.smt3, tests/disamb-arith.smt3
It is much clearer to view overloading as an instance of shadowing where the last bound term takes precendence.
=> Reverse policy for overloads

src/type_checker.cpp, user_manual.md
This makes it so that e.g. `(+ true false)` is ill-typed in the cvc5 signature. Its type previously would be `(arith_typeunion Bool Bool)`, which is ground and evaluatable.  This makes the type checker discard any such type.
=> Do not permit types that are ground and evaluatable

NEWS.md, src/expr_parser.cpp, src/state.cpp, tests/CMakeLists.txt, tests/implicit-then-var.eo, tests/opaque-inline.eo, user_manual.md
Also adds documentation to the user manual about `:opaque`.  
This bug occurs when using the syntax `(<opaque-op> <index>* <child>*)`.
This did not impact cvc5 1.2.0 since we always use the style `(_ (<opaque-op> <index>*) <child>*)`.  However, this may change soon.
=> Fix bug when appling operators with opaque arguments

NEWS.md, src/expr_parser.cpp, src/main.cpp, src/parser.cpp, src/state.cpp, src/state.h, src/type_checker.cpp, tests/arith-eval.eo, tests/mixed-arith.eo, tests/overloading-arith.eo, tests/overloading-binder.eo, tests/overloading.eo, tests/typeof.eo, user_manual.md
This makes the options `--no-normalize-dec`, `--no-normalize-hex`, `--binder-fresh`, and `--no-parse-let` apply only when reference parsing.
It simplifies the user manual to explain evaluation in terms of the core operators and not based on the syntax/options.
It adds a new option `--normalize-num` which will allow us to do SMT-LIB-compliant reference checking for QF_LRA, where numerals should be parsed as rationals.  Like the above options, this applies only to reference parsing.
This is a simpler alternative to https://github.com/cvc5/ethos/pull/66.
=> Make normalize options apply only to reference files

NEWS.md, src/cmd_parser.cpp, src/cmd_parser.h, src/expr_parser.cpp, src/expr_parser.h, src/main.cpp, src/parser.cpp, src/parser.h, src/state.cpp, src/state.h, user_manual.md
This makes the command line options apply to "proof files".
It distinguishes this as a 3rd type of input in the user manual.
=> Distinguish signature parsing from proof parsing

src/util/filesystem.cpp, src/util/filesystem.h
This is a prerequisite for supporting Windows builds.
=> Make std::filesystem code work again

NEWS.md, src/expr_info.h, src/state.cpp, tests/CMakeLists.txt, tests/overload-standalone.eo
Previously we were using a policy of handling overloaded symbols that did not update the symbol table when a symbol was overloaded but instead kept a reference to it via the original expression. When an overloaded expression was applied, it would be disambiguated based on the other expressions that had the same name.
This was incorrect for overloaded symbols that appear in unapplied positions, where we would always take the oldest expression.
This fixes the issue by always updating the symbol table and by carrying the overloads to the new expression. This simplifies the logic a bit when expressions are unbound.
=> Fix handling of overloaded symbols in standalone positions

src/type_checker.cpp
For example, before this commit (eo::list_find or (and a b b) a) == -1
=> Check if head is in list form before evaluating eo::list_find

src/state.cpp, tests/CMakeLists.txt, tests/simul-overload.eo
The bug would cause shadowed symbols to be spuriously unbound due to the order in which we were processing them when the shadowing context was popped.
This would only occur if we parsed a binder that simultaneously shadowed 2 symbols at once.
A regression is added that demonstrates the issue.
=> Fix bug involving simulataneous shadowing

NEWS.md, src/cmd_parser.cpp, src/kind.cpp, src/kind.h, src/state.cpp, src/state.h, src/type_checker.cpp, tests/CMakeLists.txt, tests/datatypes-split-rule.eo, tests/singular-datatype.eo, user_manual.md
This adds a way `eo::dt_constructors` to extract the definition of datatypes (their corresponding list of constructors) and `eo::dt_selectors` to extract the definition of datatype constructors (their corresponding list of selectors).  It adds an ordinary type `eo::List` that is part of the assumed background signature for this purpose.
Also fixes the parser for `declare-datatype` (the singular form of datatypes, which had not been tested).
=> Add support for `eo::dt_constructors` and `eo::dt_selectors` to inspect datatypes and datatype constructors

src/expr.cpp, src/state.cpp
Adds output so that decimal `0.25` is printed as `(! 1/4 :decimal)` instead of silently printing as `1/4`.   This led to confusion on https://github.com/cvc5/ethos/issues/88.
Also throws a warning if overloading fails to find a suitable operator. This warning is currently being thrown on the CPC signature on cvc5 main, which needs to be addressed.
=> Add two minor changes to Ethos output

.github/actions/upload-artifact/action.yml, .github/workflows/main.yml, COPYING, licenses/lgpl-3.0.txt
Licensing information is included with all artifacts. The Windows artifact includes the necessary libraries, which are typically not installed on the system, along with the ethos binary.
=> ci: Add platform-dependent artifact setup

src/expr_parser.cpp, src/type_checker.cpp
Fixes https://github.com/cvc5/ethos/issues/94. Fixes https://github.com/cvc5/ethos/issues/95.
Error on https://github.com/cvc5/ethos/issues/94 is now:
```
Error: /space/ajreynol/ethos/tc-fail.eo:11.54: Type checking application failed when applying la_generic
Children: [(! 1 :decimal), (! 1 :decimal)]
Message: Incorrect arity for la_generic, which expects 1 arguments and 0 premises but 2 arguments and 0 premises were provided
```
Error on https://github.com/cvc5/ethos/issues/95 is now:
```
Error: /space/ajreynol/ethos/tc-fail2.eo:6.3: Failed to bind symbol rule, since the symbol has already been defined
=> Improvements to error messages

src/main.cpp
This pull request fixes an issue where attempting to check the file extension using substr could cause an out of range error if the file name is shorter than 3 characters.
Added a condition to ensure the file name length is at least 3 before performing the substr operation.
It will prevent potential crashes or undefined behavior when handling short file names.
=> Fix out of range error in file extension check

src/state.cpp, tests/CMakeLists.txt, tests/segfault-98.eo
Fixes https://github.com/cvc5/ethos/issues/98.
It seems that depending on how line 245 is executed, we could deref the expression and delete `ai` before updating the map. This stores a temporary expression to avoid this issue.
=> Fix segfault for overloads

src/main.cpp
Added error handling to check for a missing trace tag after the -t option. Now displays an appropriate error message instead of causing a segmentation fault.
=> Fix segfault when trace tag is missing after -t option

.github/workflows/main.yml
This aligns the set of platforms supported by ethos with those supported by cvc5.
=> ci: Build ethos Linux arm64 binaries

src/expr.h, src/lexer.h
GCC 15 has streamlined some headers, with the result that cstdint.h is no longer implicitly included in some places where it used to be.  The ethos build fails with error messages such as this:
```
In file included from /builddir/build/BUILD/ethos-0.1.1-build/ethos-ethos-0.1.1/src/lexer.cpp:9:
/builddir/build/BUILD/ethos-0.1.1-build/ethos-ethos-0.1.1/src/lexer.h:28:3: error: ‘uint32_t’ does not name a type
28 |   uint32_t d_line;
|   ^~~~~~~~
/builddir/build/BUILD/ethos-0.1.1-build/ethos-ethos-0.1.1/src/lexer.h:21:1: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
```
=> Explicitly #include cstdint.h for GCC 15

NEWS.md, src/attr.cpp, src/attr.h, src/cmd_parser.cpp, src/expr_parser.cpp, src/expr_parser.h, src/kind.cpp, src/kind.h, src/state.cpp, src/state.h, src/type_checker.cpp, tests/CMakeLists.txt, tests/datatypes-split-rule-param-uinst.eo, tests/datatypes-split-rule-param.eo, tests/param-dt-parse-amb-fun.eo, tests/param-dt-parse.eo, user_manual.md
This PR ensures ethos can properly parse and type check ambiguous datatype constructors in the SMT-LIB 2.X standard.
Say a datatype constructor is "ambiguous" if it of type:
```
(-> T1 ... Tn T)
```
where some free parameter of T is not contained in the free parameters of T1...Tn. (Note n may be 0).
To support ambiguous datatype constructors in Eunoia/Ethos, we require several things.
**(1) Their declared type is made unambiguous.**
In particular, all ambiguous datatype constructors are instead defined to be of type:
```
(-> (Quote T) T1 ... Tn T)
```
This is done automatically, so that for:
```
(declare-datatypes ((List 1)) ((par (X)((nil) (cons (head X) (tail (List X)))))))
```
If the user asked for the types of the constructors, they would get:
```
(eo::typeof nil) == (-> (Quote (List …
```
=> Support ambiguous parameteric datatype constructors

.github/actions/upload-artifact/action.yml, .github/workflows/main.yml
The binaries built in CI are currently used to publish new releases. It also updates the Ubuntu runner to version 22.04, as 20.04 is now deprecated.
=> ci: Build static binaries in CI

src/expr_parser.cpp, src/main.cpp, src/state.cpp, src/state.h, src/stats.cpp, src/stats.h, src/type_checker.cpp, src/type_checker.h, user_manual.md
This adds a new class of statistics that counts the number of calls to programs, which can enable more fine grained profiling.
This also corrects a minor inconsistency in oracles/programs introduced in https://github.com/cvc5/ethos/pull/110, where the check for "stuck" terms should be applied uniformly for programs and oracles.
Example output:
```
========================================================================
mkExprCount = 793
newExprCount = 700
deleteExprCount = 69
symCount = 226
litCount = 7
time = 23904
====================================================================================
Rule  #      t                t/#       #mkExpr   
====================================================================================
arith_sum_ub: 1      1565 (6.5%)      1565      46 …
```
=> Add --stats-all

src/cmd_parser.cpp, src/expr_info.h, src/kind.cpp, src/state.cpp, src/state.h, tests/CMakeLists.txt, tests/overload-define.eo
The previous solution was overly complicated and could lead to subtle issues with garbage collection.
Fixes https://github.com/cvc5/ethos/issues/115.
Also makes a minor fix to the printer and removes a spurious assertion encountered while debugging this issue.
=> Fix and simplify handling of overloaded symbols

NEWS.md, src/expr.cpp, src/main.cpp, src/state.cpp, src/state.h, user_manual.md
Fixes https://github.com/cvc5/ethos/issues/121.
=> Dagify output by default, change syntax to eo::define

NEWS.md, src/type_checker.cpp, user_manual.md
`eo::typeof` is an exceptional case in that it can return a term with free parameters. It is the only such operator that may do so.  This behavior is fairly unintuitive and moreover allows non-first-class terms e.g. `Quote` to appear in terms.
We instead make it so that `eo::typeof` does not evaluate if the type is non-ground.
=> Do not return non-ground types with eo::typeof

src/expr_parser.cpp, src/kind.cpp, src/kind.h, src/state.cpp
This prevents us from using e.g. `->`, `_`, `as`, `eo::*` as arguments to other functions.
This was not properly guarded since these symbols are bound in the symbol table, and not lexed as heads of applications for simplicity.
=> Guard use of builtin operators in argument positions

NEWS.md, src/state.cpp, tests/CMakeLists.txt, tests/pairwise-singleton.eo, user_manual.md
Following the discussion on https://github.com/cvc5/ethos/issues/118.
=> Reduce pairwise and chainable for single arguments to neutral element

user_manual.md
Added some fixes to formatting syntax (e.g., <term> was changed to `<term>`, so it can be displayed after processing the file).
=> minor fixes in Formal def. of preprocessor

src/lexer.cpp
Initially I wanted to support the syntax `#b`, but this was never properly added and can be accomplished by `(eo::to_bin 0 0)`.
Currently we give an unintuitive error, this fixes this case.
=> Do not permit empty binary/hexadecimal constants

NEWS.md, src/cmd_parser.cpp, user_manual.md
Also drops support for general extensions to the syntax for program/declare-rule, which we decided not to focus on.
=> Require programs and oracles to have at least one argument

src/state.cpp, tests/CMakeLists.txt, tests/type-var-exists.eo
This corrects an issue in how binders were parsed: in certain contexts, we could construct a variable whose type is non-ground.  However, based on the understood desugaring of binders which uses `(eo::var <name> <type>)`, this application should wait to evaluate until `<type>` becomes ground.
A regression is added that fails before but now succeeds.
=> Fix handling of bound variables with non-ground type

user_manual.md
These features are deprecated and should use the syntax for `declare-parameterized-const` instead.
=> Do not mention :var or :implicit term attributes in user manual

NEWS.md, src/expr_parser.cpp, src/kind.cpp, src/kind.h, src/state.cpp, src/type_checker.cpp, tests/CMakeLists.txt, tests/array-ext-implicit-type-infer.eo, tests/datatypes-split-rule-param-uinst.eo, tests/datatypes-split-rule-param.eo, tests/emptylist.eo, tests/nground-nil-v3.eo, tests/premise-list-nary-cong-2.eo, tests/premise-list-nary-cong.eo, tests/use-match.eo
This changes type checking such that the free parameters of the types of parameters are also bound when that parameter is instantiated.
The motivation for this change:
- It makes the relationship between quote arrow and ordinary arrow more intuitive, i.e. quoting an argument does not impact its behavior.
- Ensures the types of parameters are taken into account instead of ignored.
- Allows for more powerful proof rules, e.g. the array extensionality rule added in a regression on this PR.
To implement this, we introduce a new distinguished operator `eo::param` or "annotated parameter" that "wraps" a parameter with its type. The match algorithm now treats this operator as a special case, matching the second argument with the type of the term that is matched.  This operator is used internally …
=> Update type system with annotated parameters

NEWS.md, src/kind.cpp, src/kind.h, src/state.cpp, src/state.h, src/type_checker.cpp, tests/CMakeLists.txt, tests/is-eq-tests.eo, tests/type-var-exists.eo, user_manual.md
This changes the semantics of `eo::is_eq` such that it returns "false" for two terms that are both stuck.  This also impacts the semantics of `eo::requires`, whose semantics depends on `eo::is_eq`.
It introduces `eo::eq` and `eo::is_ok`, which are the more primitive operators that `eo::is_eq` can be described in terms of.
=> Change eo::is_eq, add eo::eq and eo::is_ok

NEWS.md, src/main.cpp, user_manual.md
An example with `eo::eq` was inaccurate.
=> More improvements and fix to user manual examples, prepare release
